### ISSUE TITLE
解决 python 中读写文件编码错误

### ISSUE THREAD

**Issue by SingularityZed** [zhangzp9970/GnomeBingLockScreen#1]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 242: illegal multibyte sequence.
解决办法1.
FILE_OBJECT= open('order.log','r', encoding='UTF-8')

解决办法2.
FILE_OBJECT= open('order.log','rb')

所以：
with open(json_file,"r") as f:  ==>with open(json_file,"rb") as f:

**Comment by zhangzp9970** [comment]
感谢您的反馈，已经修改了相关代码。
由于我在运行程序时并未出现过此类错误，想了解一下您的系统类型以及环境变量`$LC_NAME`
